name: Hello World Pipeline
on:
  workflow_dispatch:
  push:
  workflow_dispatch:
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"